version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: strawwallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strawwalletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local
