#Database and Mail Sender Configs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strawwalletdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
server:
  servlet:
    context-path: /api/v1
jwt:
  secret: dGVzdGVfc2VjcmV0X2tleV9mb3Jfand0X3Rva2VuX2dlbmVyYXRpb25fMTIzNDU2Nzg5MA==
  expiration: 86400000
application:
  activation:
    url: ${FLUXXOAPP_BACKEND_URL}
